[2025-02-11T20:37:43.930+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T20:37:43.963+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-11T15:37:34-05:00 [queued]>
[2025-02-11T20:37:43.980+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-11T15:37:34-05:00 [queued]>
[2025-02-11T20:37:43.981+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T20:37:44.004+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-11 20:37:34+00:00
[2025-02-11T20:37:44.015+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3613) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T20:37:44.018+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_to_scrape_and_upload', 'Upload_data_to_s3', 'manual__2025-02-11T15:37:34-05:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/scrape_upload_dag.py', '--cfg-path', '/tmp/tmp9mnpqse1']
[2025-02-11T20:37:44.023+0000] {standard_task_runner.py:72} INFO - Started process 3614 to run task
[2025-02-11T20:37:44.023+0000] {standard_task_runner.py:105} INFO - Job 135: Subtask Upload_data_to_s3
[2025-02-11T20:37:44.110+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-11T15:37:34-05:00 [running]> on host ecdf8258250e
[2025-02-11T20:37:44.277+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_to_scrape_and_upload' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T20:37:34+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T15:37:34-05:00'
[2025-02-11T20:37:44.279+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T20:38:44.909+0000] {job.py:229} INFO - Heartbeat recovered after 55.77 seconds
[2025-02-11T20:38:47.365+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-11T20:39:27.749+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-11T20:39:38.323+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-02-11T20:39:38.453+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T20:39:38.459+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
